apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-war
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: default
  source: 
    path: openshift
    repoURL: https://github.com/jfdenise/go-to-openshift
    targetRevision: http_github.com_jfdenise_my-war_revision_main
  syncPolicy: 
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=false
