apiVersion: v1
kind: Secret
metadata:
  name: dockerconfig-secret
stringData:
  config.json: |
    {
      "auths" : {
        "quay.io" : {
          "auth" : "amRlbmlzZStnbG93X3BpcGVsaW5lOlZJOTlCRzZFSzFDQ0c0TUJFRFQ1TDFYU0wxOUpCV05PNEs4NkVINFEzNk1WUUNJSUhLTENBWTZET1BFNU03UUk=",
          "email": ""
        }
      }
    }