kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: wildfly-glow-pipeline
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: wildfly-glow-pipeline
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin

