apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: wildfly-glow-pipeline
spec:
  params:
    - name: gitUrl
    - name: gitRevision
      default: ""
  workspaces:
    - name: shared-data
    - name: ssh-creds
    - name: internal-repo
    - name: dockerconfig
  tasks:
    - name: setup
      taskRef:
        name: wildfly-setup-task
      workspaces:
        - name: sources
          workspace: shared-data
        - name: internal-repo
          workspace: internal-repo
    - name: identify-branch
      params:
        - name: gitUrl
          value: "$(params.gitUrl)"
        - name: gitRevision
          value: "$(params.gitRevision)"
      taskRef:
        name: wildfly-identify-branch-task
      runAfter: 
        - setup
    - name: git-clone-user-repo
      taskRef:
        name: git-clone
        kind: ClusterTask
      workspaces:
        - name: output
          workspace: shared-data
      params:
        - name: url
          value: "$(params.gitUrl)"
        - name: revision
          value: "$(params.gitRevision)"
        - name: subdirectory
          value: "$(tasks.setup.results.contextDir)"
      runAfter: 
        - identify-branch
    - name: git-clone-internal-repo
      taskRef:
        name: git-clone
        kind: ClusterTask
      workspaces:
        - name: output
          workspace: internal-repo
        - name: ssh-directory
          workspace: ssh-creds
      params:
        - name: url
          value: "git@github.com:jfdenise/go-to-openshift"
        - name: revision
          value: "$(tasks.identify-branch.results.branchToPull)"
        - name: subdirectory
          value: "$(tasks.setup.results.contextDir)"
      runAfter: 
        - identify-branch
    - name: wildfly-glow-generate-provision
      taskRef:
        name: wildfly-glow-generator-task
      params:
        - name: gitUrl
          value: "$(params.gitUrl)"
        - name: gitRevision
          value: "$(params.gitRevision)"
        - name: contextDir
          value: "$(tasks.setup.results.contextDir)"
        - name: newBranch
          value: "$(tasks.identify-branch.results.newBranch)"
      workspaces:
        - name: sources
          workspace: shared-data
        - name: current-repo
          workspace: internal-repo
      runAfter: 
        - git-clone-user-repo
        - git-clone-internal-repo
    - name: build-server-image
      taskRef:
        name: buildah
        kind: ClusterTask
      when:
      - input: "$(tasks.wildfly-glow-generate-provision.results.needBuildServerImage)"
        operator: in
        values: ["true"]
      params:
        - name: IMAGE
          value: "$(tasks.wildfly-glow-generate-provision.results.serverImage)"
        - name: DOCKERFILE
          value: "$(tasks.wildfly-glow-generate-provision.results.serverDockerfile)"
        - name: CONTEXT
          value: "$(tasks.setup.results.contextDir)/$(tasks.wildfly-glow-generate-provision.results.provisioning)"
        - name: TLSVERIFY
          value: "false" 
      runAfter: 
        - wildfly-glow-generate-provision
      workspaces:
        - name: source
          workspace: shared-data
        - name: dockerconfig
          workspace: dockerconfig
    - name: build-app-image
      taskRef:
        name: buildah
        kind: ClusterTask
      when:
      - input: "$(tasks.wildfly-glow-generate-provision.results.needBuildAppImage)"
        operator: in
        values: ["true"]
      params:
        - name: IMAGE
          value: "$(tasks.wildfly-glow-generate-provision.results.appImage)"
        - name: DOCKERFILE
          value: "$(tasks.wildfly-glow-generate-provision.results.appDockerfile)"
        - name: CONTEXT
          value: "$(tasks.setup.results.contextDir)/$(tasks.wildfly-glow-generate-provision.results.provisioning)"
        - name: TLSVERIFY
          value: "false"
      runAfter: 
        - build-server-image
      workspaces:
        - name: source
          workspace: shared-data
        - name: dockerconfig
          workspace: dockerconfig
    - name: git-create-branch-and-push
      taskRef:
        name: git-cli
        kind: ClusterTask
      params:
        - name: GIT_USER_NAME
          value: jfdenise
        - name: GIT_USER_EMAIL
          value: jfdenise@gmail.com
        - name: GIT_SCRIPT
          value: |
           cd $(tasks.setup.results.contextDir) 
           git config --global --add safe.directory /workspace/source/$(tasks.setup.results.contextDir)
           rev=$(tasks.identify-branch.results.newBranch)
           exists=`git ls-remote --heads git@github.com:jfdenise/go-to-openshift "refs/heads/${rev}" | wc -l`
           if [ "${exists}" = "1" ]; then
             echo "A branch already exists"
             git fetch origin "$(tasks.identify-branch.results.newBranch)"
             git checkout "$(tasks.identify-branch.results.newBranch)"
           else
             git checkout -b "$(tasks.identify-branch.results.newBranch)"
           fi
           # Remove all
           rm -rf ./*
           if [ -d  ".s2i" ]; then
             rm -rf .s2i
           fi
           ls -al $(workspaces.input.path)/$(tasks.setup.results.contextDir)/$(tasks.wildfly-glow-generate-provision.results.contentLocation)/
           cp -r $(workspaces.input.path)/$(tasks.setup.results.contextDir)/$(tasks.wildfly-glow-generate-provision.results.contentLocation)/* .
           if [ -d  "$(workspaces.input.path)/$(tasks.setup.results.contextDir)/$(tasks.wildfly-glow-generate-provision.results.contentLocation)/.s2i" ]; then
             cp -rf $(workspaces.input.path)/$(tasks.setup.results.contextDir)/$(tasks.wildfly-glow-generate-provision.results.contentLocation)/.s2i .
           fi
           ls -al .
           git status
           if [ -n "$(git status --porcelain)" ]; then
             git add *
             git add */.*
             git commit -m "Commit from WildFly Glow pipeline"
             git push origin "$(tasks.identify-branch.results.newBranch)"
           else
             echo "No changes to commit";
           fi
      workspaces:
        - name: source
          workspace: internal-repo
        - name: input
          workspace: shared-data
        - name: ssh-directory
          workspace: ssh-creds
      runAfter: 
        - build-app-image
  finally:
    - name: cleanup
      taskRef:
        name: wildfly-cleanup-task
      params:
        - name: contextDir
          value: "$(tasks.setup.results.contextDir)"
      workspaces:
        - name: sources
          workspace: shared-data
        - name: internal-repo
          workspace: internal-repo

