apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: wildfly-glow-pipeline
spec:
  params:
    - name: gitRepo
    - name: gitRepoOwner
    - name: gitRepoProject
    - name: gitRevision
      default: ""
    - name: userProject
      default: ""
    - name: gitopsProject
      default: ""
    - name: deploy
      default: "true"
    - name: "internalGitRepo"
    - name: "applicationImageRepository"
    - name: "serverImageRepository"
  workspaces:
    - name: shared-data
    - name: ssh-creds
    - name: internal-repo
    - name: dockerconfig
    - name: app-repo
  tasks:
    - name: setup
      taskRef:
        name: wildfly-setup-task
      workspaces:
        - name: sources
          workspace: shared-data
        - name: internal-repo
          workspace: internal-repo
        - name: app-repo
          workspace: app-repo
      params:
        - name: gitRepo
          value: $(params.gitRepo)
        - name: gitRepoOwner
          value: $(params.gitRepoOwner)
        - name: gitRepoProject
          value: "$(params.gitRepoProject)"
        - name: gitRevision
          value: "$(params.gitRevision)"
    - name: identify-cluster
      taskRef:
        name: wildfly-detect-openshift-task
      runAfter: 
        - setup
    - name: git-clone-app-repo
      taskRef:
        name: git-clone
        kind: ClusterTask
      workspaces:
        - name: output
          workspace: app-repo
        - name: ssh-directory
          workspace: ssh-creds
      params:
        - name: url
          value: "git@$(params.gitRepo):$(params.gitRepoOwner)/$(params.gitRepoProject)"
        - name: revision
          value: "$(params.gitRevision)"
        - name: subdirectory
          value: "$(tasks.setup.results.contextDir)"
      runAfter: 
        - setup
    - name: git-clone-internal-repo
      taskRef:
        name: git-clone
        kind: ClusterTask
      workspaces:
        - name: output
          workspace: internal-repo
        - name: ssh-directory
          workspace: ssh-creds
      params:
        - name: url
          value: "$(params.internalGitRepo)"
        - name: revision
          value: "init"
        - name: subdirectory
          value: "$(tasks.setup.results.contextDir)"
      runAfter: 
        - setup
    - name: setup-internal-repo
      taskRef:
        name: git-cli
        kind: ClusterTask
      params:
        - name: GIT_USER_NAME
          value: jfdenise
        - name: GIT_USER_EMAIL
          value: jfdenise@gmail.com
        - name: GIT_SCRIPT
          value: |
           cd $(tasks.setup.results.contextDir) 
           git config --global --add safe.directory /workspace/source/$(tasks.setup.results.contextDir)
           newBranch=$(tasks.setup.results.appBranch)
           exists=`git ls-remote --heads $(params.internalGitRepo) "refs/heads/${newBranch}" | wc -l`
           if [ "${exists}" = "1" ]; then
             echo "$newBranch already exists"
             git fetch origin "$newBranch"
             git checkout "$newBranch"
           fi
      workspaces:
        - name: source
          workspace: internal-repo
        - name: ssh-directory
          workspace: ssh-creds
      runAfter: 
        -  git-clone-internal-repo
    - name: wildfly-glow-generate
      taskRef:
        name: wildfly-glow-generator-task
      params:
        - name: gitRepo
          value: "$(params.gitRepo)/$(params.gitRepoOwner)/$(params.gitRepoProject)"
        - name: gitRevision
          value: "$(params.gitRevision)"
        - name: gitCommit
          value: "$(tasks.git-clone-app-repo.results.commit)"
        - name: gitCommitterDate
          value: "$(tasks.git-clone-app-repo.results.committer-date)"
        - name: contextDir
          value: "$(tasks.setup.results.contextDir)"
        - name: newBranch
          value: "$(tasks.setup.results.appBranch)"
        - name: userProject
          value: "$(params.userProject)"
        - name: applicationImageRepository
          value: "$(params.applicationImageRepository)"
        - name: serverImageRepository
          value: "$(params.serverImageRepository)"
        - name: openshift
          value: "$(tasks.identify-cluster.results.openshift)"
      workspaces:
        - name: sources
          workspace: shared-data
        - name: current-repo
          workspace: internal-repo
        - name: app-repo
          workspace: app-repo
      runAfter: 
        - git-clone-app-repo
        - setup-internal-repo
        - identify-cluster
    - name: check-server-image-exists
      taskRef:
        name: wildfly-check-image-exists-task
     # If we enable this condition, and we don't need to build a server image, all following tasks are not executed. Bug in Tekton?'
     # when:
     # - input: "$(tasks.wildfly-glow-generate.results.needBuildServerImage)"
     #   operator: in
     #   values: ["true"]
      params:
        - name: image
          value: "$(tasks.wildfly-glow-generate.results.serverImage)"
      runAfter: 
        - wildfly-glow-generate
    - name: wildfly-provision
      taskRef:
        name: wildfly-provision-task
      when:
      - input: "$(tasks.check-server-image-exists.results.exists)"
        operator: in
        values: ["false"]
      params:
        - name: contextDir
          value: "$(tasks.setup.results.contextDir)"
      workspaces:
        - name: sources
          workspace: shared-data
        - name: app-repo
          workspace: app-repo
      runAfter: 
        - check-server-image-exists
    - name: build-server-image
      taskRef:
        name: buildah
        kind: ClusterTask
      when:
      - input: "$(tasks.check-server-image-exists.results.exists)"
        operator: in
        values: ["false"]
      params:
        - name: IMAGE
          value: "$(tasks.wildfly-glow-generate.results.serverImage)"
        - name: DOCKERFILE
          value: "$(tasks.wildfly-glow-generate.results.serverDockerfile)"
        - name: CONTEXT
          value: "$(tasks.setup.results.contextDir)/$(tasks.wildfly-glow-generate.results.dockerContext)"
        - name: TLSVERIFY
          value: "false"
      runAfter: 
        - wildfly-provision
      workspaces:
        - name: source
          workspace: shared-data
        - name: dockerconfig
          workspace: dockerconfig
    - name: check-app-image-exists
      taskRef:
        name: wildfly-check-image-exists-task
# If we enable this condition, and we don't need to build an app image, all following tasks are not executed. Bug in Tekton?'
#      when:
#      - input: "$(tasks.wildfly-glow-generate.results.needBuildAppImage)"
#        operator: in
#        values: ["true"]
      params:
        - name: image
          value: "$(tasks.wildfly-glow-generate.results.appImage)"
      runAfter: 
        - build-server-image
    - name: build-app-image
      taskRef:
        name: buildah
        kind: ClusterTask
      when:
      - input: "$(tasks.check-app-image-exists.results.exists)"
        operator: in
        values: ["false"]
      params:
        - name: IMAGE
          value: "$(tasks.wildfly-glow-generate.results.appImage)"
        - name: DOCKERFILE
          value: "$(tasks.wildfly-glow-generate.results.appDockerfile)"
        - name: CONTEXT
          value: "$(tasks.setup.results.contextDir)/$(tasks.wildfly-glow-generate.results.dockerContext)"
        - name: TLSVERIFY
          value: "false"
      runAfter: 
        - check-app-image-exists
      workspaces:
        - name: source
          workspace: shared-data
        - name: dockerconfig
          workspace: dockerconfig
    - name: git-update-deployment-repo-and-push
      taskRef:
        name: git-cli
        kind: ClusterTask
      params:
        - name: GIT_USER_NAME
          value: jfdenise
        - name: GIT_USER_EMAIL
          value: jfdenise@gmail.com
        - name: GIT_SCRIPT
          value: |
           cd $(tasks.setup.results.contextDir) 
           git config --global --add safe.directory /workspace/source/$(tasks.setup.results.contextDir)
           rev=$(tasks.setup.results.appBranch)_deployment
           userRev=$(params.gitRevision)_deployment
           # Add the user_deployment repo
           git remote add userRepo git@$(params.gitRepo):$(params.gitRepoOwner)/$(params.gitRepoProject)
           git remote update userRepo

           exists=`git ls-remote --heads $(params.internalGitRepo) "refs/heads/${rev}" | wc -l`
           if [ "${exists}" = "1" ]; then
             echo "A branch already exists"
             git fetch origin "${rev}"
             git checkout "${rev}"
           else
             git checkout -b init_internal_deployment --track origin/init
             git checkout -b "${rev}"
           fi
           if [ -d "$(workspaces.input.path)/$(tasks.setup.results.contextDir)/$(tasks.wildfly-glow-generate.results.deploymentLocation)" ]; then
             cp -r $(workspaces.input.path)/$(tasks.setup.results.contextDir)/$(tasks.wildfly-glow-generate.results.deploymentLocation)/* .
           fi
           # The user deployment branch
           exists=`git ls-remote --heads userRepo "refs/heads/${userRev}" | wc -l`
           if [ "${exists}" = "1" ]; then
             echo "A branch already exists"
             git fetch userRepo "${userRev}"
             git branch "${userRev}" --track userRepo/"$userRev"
           else
             # Create a branch that we will use to push to the user space
             git checkout -b user_init_internal --track userRepo/init
             git checkout -b "$userRev"
             # Switch back to the internal deployment branch
             git checkout "${rev}"
           fi
           if [ -d "$(workspaces.input.path)/$(tasks.setup.results.contextDir)/$(tasks.wildfly-glow-generate.results.deploymentLocation)" ]; then
             cp -r $(workspaces.input.path)/$(tasks.setup.results.contextDir)/$(tasks.wildfly-glow-generate.results.deploymentLocation)/* .
           fi
           ls -al .
           git status
           changes="$(git status --porcelain)"
           if [ -n "$changes" ]; then
             # Commit the changes
             git add *
             git commit -m "Commit from WildFly Glow pipeline. 
             $changes"
             commitId=`git rev-parse HEAD`
             # Build the patch
             git format-patch -1 HEAD --stdout > changes.patch
             echo "Patch content"
             cat changes.patch
             
             # Check if the patch can be applied to the user repo
             git checkout $userRev
             # Use 3way to ignore added files
             res=$(git apply --3way changes.patch --check 2>&1)
             if [[ "$res" =~  .*" with conflicts" ]]; then
               echo "ERROR: Failure applying changes to $(params.gitRepo):$(params.gitRepoOwner)/$(params.gitRepoProject) branch $userRev"
               echo "Conflicting patch generated in pipeline-conflict.patch file, make sure to manually merge the changes if needed."
               mv changes.patch pipeline-conflict.patch
               git add pipeline-conflict.patch
               git commit -m "A conflict occured, check 'pipeline-conflict.patch' file, fix the conflict then call 'git apply pipeline-conflict.patch', delete the patch file then restart the pipeline"
               git push userRepo $userRev
               exit 1
             else
               rm changes.patch
               echo "Success, can apply changes to $(params.gitRepo):$(params.gitRepoOwner)/$(params.gitRepoProject) branch $userRev "
               git cherry-pick $commitId || echo "Empty commit, nothing to cherry-pick"
               git push userRepo $userRev
               git push origin "${rev}"
             fi
           fi           
      workspaces:
        - name: source
          workspace: internal-repo
        - name: input
          workspace: shared-data
        - name: ssh-directory
          workspace: ssh-creds
      runAfter: 
        -  build-app-image
    - name: git-update-internal-repo-and-push
      taskRef:
        name: git-cli
        kind: ClusterTask
      params:
        - name: GIT_USER_NAME
          value: jfdenise
        - name: GIT_USER_EMAIL
          value: jfdenise@gmail.com
        - name: GIT_SCRIPT
          value: |
           cd $(tasks.setup.results.contextDir) 
           git config --global --add safe.directory /workspace/source/$(tasks.setup.results.contextDir)
           rev=$(tasks.setup.results.appBranch)
           exists=`git ls-remote --heads $(params.internalGitRepo) "refs/heads/${rev}" | wc -l`
           if [ "${exists}" = "1" ]; then
             echo "A branch already exists"
             git fetch origin "$rev"
             git checkout "$rev"
           else
             git checkout -b init_internal --track origin/init
             git checkout -b "$rev"
           fi
           ls -al $(workspaces.input.path)/$(tasks.setup.results.contextDir)/$(tasks.wildfly-glow-generate.results.contentLocation)/
           cp -r $(workspaces.input.path)/$(tasks.setup.results.contextDir)/$(tasks.wildfly-glow-generate.results.contentLocation)/* .
           ls -al .
           git status
           if [ -n "$(git status --porcelain)" ]; then
             git add *
             git commit -m "Commit from WildFly Glow pipeline"
             git push origin "$rev"
           fi
           # Checkout the deployment branch for the deploy. TO CLEAN!!!!
           git checkout "${rev}"_deployment
           echo CURRENT LOCATION: $PWD
           ls -l
      when:
      - input: "$(tasks.wildfly-glow-generate.results.needBuildAppImage)"
        operator: in
        values: ["true"]
      workspaces:
        - name: source
          workspace: internal-repo
        - name: input
          workspace: shared-data
        - name: ssh-directory
          workspace: ssh-creds
      runAfter: 
        -  git-update-deployment-repo-and-push
    - name: deploy
      taskRef:
        name: wildfly-deploy-task
      when:
      - input: "$(params.deploy)"
        operator: in
        values: ["true"]
      workspaces:
        - name: internal-deployment-repo
          workspace: internal-repo
      params:
        - name: contextDir
          value: "$(tasks.setup.results.contextDir)"
        - name: gitopsProject
          value: "$(params.gitopsProject)"
      runAfter: 
        - git-update-internal-repo-and-push
  finally:
    - name: cleanup
      taskRef:
        name: wildfly-cleanup-task
      params:
        - name: contextDir
          value: "$(tasks.setup.results.contextDir)"
      workspaces:
        - name: sources
          workspace: shared-data
        - name: internal-repo
          workspace: internal-repo
        - name: app-repo
          workspace: app-repo

