apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: wildfly-argocd-deploy-task
spec:
  params:
    - name: contentLocation
      description: Where to find resources
    - name: appName
      description: application name
    - name: namespace
      description: namespace
    - name: gitURL
      description: git
    - name: gitRevision
      description: rev
  workspaces:
    - name: sources
      description: The src dir
      
  steps:
    - name: deploy
      securityContext:
        runAsUser: 0
      image: "image-registry.openshift-image-registry.svc:5000/openshift/cli:latest"
      env:
        - name: RESOURCES_PATH
          value: $(workspaces.sources.path)/$(params.contentLocation)/resources/build
      script: |
        