apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: wildfly-import-image-task
spec:
  params:
    - name: appImage
      description: application image
    - name: tag
      description: application image tag
    - name: appName
      description: AppName used for the image stream
    - name: contextDir
      description: Context dir
  workspaces:
    - name: current-repo
      description: The current repo    
  steps:
    - name: import-image
      securityContext:
        runAsUser: 0
      image: "image-registry.openshift-image-registry.svc:5000/openshift/cli:latest"
      script: |
        echo "Importing Image $(params.appImage)"
        oc create -f $(workspaces.current-repo.path)/$(params.contextDir)/openshift/$(params.appName)-image-stream.yaml
        oc import-image $(params.appName):$(params.tag) --from=$(params.appImage):$(params.tag)
        oc tag $(params.appName):$(params.tag) $(params.appName):latest
