apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: wildfly-build-docker-info-task
spec:
  params:
    - name: dockerContextDir
      type: string
    - name: gitContentDir
      type: string
    - name: serverImage
      type: string
    - name: appImage
      type: string
  results:
    - name: serverDockerfile
      description: where the docker file is located
    - name: appDockerfile
      description: where the docker file is located
  workspaces:
    - name: sources
      description: The src dir
  steps:
    - name: generate-docker-content
      securityContext:
        runAsUser: 0
      image: "redhat/ubi8"
      env:
        - name: DOCKER_CONTEXT_PATH
          value: $(workspaces.sources.path)/$(params.dockerContextDir)
        - name: GIT_CONTENT_PATH
          value: $(workspaces.sources.path)/$(params.gitContentDir)
      script: |
        mkdir -p $GIT_CONTENT_PATH/docker/server
        mkdir -p $DOCKER_CONTEXT_PATH/docker/server
        cat <<EOF > "$GIT_CONTENT_PATH/docker/server/Dockerfile"
        FROM quay.io/wildfly/wildfly-runtime:latest
        COPY server \$JBOSS_HOME
        USER root
        RUN chown -R jboss:root \$JBOSS_HOME && chmod -R ug+rwX \$JBOSS_HOME
        USER jboss
        EOF
        cp $GIT_CONTENT_PATH/docker/server/Dockerfile $DOCKER_CONTEXT_PATH/docker/server
        
        mkdir -p $GIT_CONTENT_PATH/docker/app
        mkdir -p $DOCKER_CONTEXT_PATH/docker/app
        
        extensions=
        if [ -d "$DOCKER_CONTEXT_PATH/extensions" ]; then
          extensions="COPY --chown=jboss:root extensions \$JBOSS_HOME/extensions"
        fi
        cat <<EOF > "$GIT_CONTENT_PATH/docker/app/Dockerfile"
        FROM $(params.serverImage)
        COPY deployments/* \$JBOSS_HOME/standalone/deployments
        $extensions
        USER root
        RUN chown -R jboss:root \$JBOSS_HOME && chmod -R ug+rwX \$JBOSS_HOME
        USER jboss
        EOF
        cp $GIT_CONTENT_PATH/docker/app/Dockerfile $DOCKER_CONTEXT_PATH/docker/app
        
        echo -n "docker/server/Dockerfile" > $(results.serverDockerfile.path)
        echo -n "docker/app/Dockerfile" > $(results.appDockerfile.path)
