apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: wildfly-build-image-task
spec:
  params:
    - name: contentLocation
      description: Where to find resources
  workspaces:
    - name: sources
      description: The src dir
      
  steps:
    - name: build-image
      securityContext:
        runAsUser: 0
      image: "image-registry.openshift-image-registry.svc:5000/openshift/cli:latest"
      env:
        - name: RESOURCES_PATH
          value: $(workspaces.sources.path)/$(params.contentLocation)/resources/build
      script: |
        oc project wildfly-images
        files=`ls $RESOURCES_PATH/*.yaml`
        for eachfile in $files
        do
          oc apply -f "$eachfile"
        done
        # Read the names of the build to start
        file="$RESOURCES_PATH/build.properties"
        while IFS="=" read -r key value; do
          case "$key" in
           "builder") builder="$value" ;;
           "runtime") runtime="$value" ;;
        esac
        done < "$file"
        oc start-build --wait $builder
        oc start-build --wait $runtime
        echo "Image has been built"