apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: wildfly-deploy-task
spec:
  params:
    - name: contentLocation
      description: Where to find resources
  workspaces:
    - name: sources
      description: The src dir
  steps:
    - name: deploy
      securityContext:
        runAsUser: 0
      image: "image-registry.openshift-image-registry.svc:5000/openshift/cli:latest"
      env:
        - name: CONTENT_PATH
          value: $(workspaces.sources.path)/$(params.contentLocation)
      script: |
        files=`ls $CONTENT_PATH/openshift/*.yaml`
        for eachfile in $files
        do
          oc apply -f "$eachfile"
        done
        echo "Application has been deployed"