apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: wildfly-helm-task
spec:
  params:
   - name: helmFile
     type: string
   - name: releaseName
     type: string
  workspaces:
    - name: sources
      description: The src dir
  steps:
    - name: helm-install
      securityContext:
        runAsUser: 0
      image: "image-registry.openshift-image-registry.svc:5000/openshift/cli:latest"
      env:
        - name: WORKSPACE_SRC_PATH
          value: $(workspaces.sources.path)
      script: |
        curl --insecure https://get.helm.sh/helm-v3.15.1-linux-amd64.tar.gz -LO
        tar xvfz helm-v3.15.1-linux-amd64.tar.gz
        ./linux-amd64/helm repo add wildfly https://docs.wildfly.org/wildfly-charts/
        relName=$(params.releaseName)
        set +e
        ret="$(./linux-amd64/helm status $relName)"
        if [ $? == 0 ]; then
          set -e
          echo starting a new build
          oc start-build $relName-build-artifacts
        else
          set -e
          echo installing helm chart...
          ./linux-amd64/helm install $(params.releaseName) -f "$WORKSPACE_SRC_PATH/$(params.helmFile)" wildfly/wildfly
        fi