apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: wildfly-detect-openshift-task
spec:
  results:
    - name: openshift
      description: True if that is openshift
  steps:
    - name: check-openshift
      securityContext:
        runAsUser: 0
      image: "image-registry.openshift-image-registry.svc:5000/openshift/cli:latest"
      script: |
        res=`oc api-resources --api-group=route.openshift.io`
        if [[ "$res" =~  .*"route.openshift.io/" ]]; then
          echo "Openshift cluster"
          echo -n "true" > $(results.openshift.path)
        else
          echo "Not Openshift cluster"
          echo -n "false" > $(results.openshift.path)
        fi
        
