apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: wildfly-glow-pipeline
spec:
  params:
    - name: gitUrl
    - name: gitRevision
      default: ""
  workspaces:
    - name: shared-data
    - name: ssh-creds
    - name: internal-repo
    - name: dockerconfig
  tasks:
    - name: setup
      taskRef:
        name: wildfly-setup-task
      workspaces:
        - name: sources
          workspace: shared-data
        - name: internal-repo
          workspace: internal-repo
    - name: git-clone-user-repo
      taskRef:
        name: git-clone
        kind: ClusterTask
      workspaces:
        - name: output
          workspace: shared-data
      params:
        - name: url
          value: "$(params.gitUrl)"
        - name: revision
          value: "$(params.gitRevision)"
        - name: subdirectory
          value: "$(tasks.setup.results.contextDir)"
      runAfter: 
        - setup
    - name: git-clone-internal-repo
      taskRef:
        name: git-clone
        kind: ClusterTask
      workspaces:
        - name: output
          workspace: internal-repo
        - name: ssh-directory
          workspace: ssh-creds
      params:
        - name: url
          value: "git@github.com:jfdenise/go-to-openshift"
        - name: revision
          value: "main"
        - name: subdirectory
          value: "$(tasks.setup.results.contextDir)"
      runAfter: 
        - setup
    - name: wildfly-glow-generate-provision
      taskRef:
        name: wildfly-glow-generator-task
      params:
        - name: gitUrl
          value: "$(params.gitUrl)"
        - name: gitRevision
          value: "$(params.gitRevision)"
        - name: sourcesDir
          value: "$(tasks.setup.results.contextDir)"
      workspaces:
        - name: sources
          workspace: shared-data
      runAfter: 
        - git-clone-user-repo
    - name: generate-docker-files
      taskRef:
        name: wildfly-build-docker-info-task
      workspaces:
        - name: sources
          workspace: shared-data
      params:
        - name: dockerContextDir
          value: "$(tasks.setup.results.contextDir)/$(tasks.wildfly-glow-generate-provision.results.provisioning)"
        - name: gitContentDir
          value: "$(tasks.setup.results.contextDir)/$(tasks.wildfly-glow-generate-provision.results.contentLocation)"
        - name: appImage
          value: "$(tasks.wildfly-glow-generate-provision.results.appImage)"
        - name: serverImage
          value: "$(tasks.wildfly-glow-generate-provision.results.serverImage)"
      runAfter: 
        - wildfly-glow-generate-provision
    - name: build-server-image
      taskRef:
        name: buildah
        kind: ClusterTask
      params:
        - name: IMAGE
          value: "$(tasks.wildfly-glow-generate-provision.results.serverImage)"
        - name: DOCKERFILE
          value: "$(tasks.generate-docker-files.results.serverDockerfile)"
        - name: CONTEXT
          value: "$(tasks.setup.results.contextDir)/$(tasks.wildfly-glow-generate-provision.results.provisioning)"
        - name: TLSVERIFY
          value: "false" 
      runAfter: 
        - generate-docker-files
      workspaces:
        - name: source
          workspace: shared-data
        - name: dockerconfig
          workspace: dockerconfig
    - name: build-app-image
      taskRef:
        name: buildah
        kind: ClusterTask
      params:
        - name: IMAGE
          value: "$(tasks.wildfly-glow-generate-provision.results.appImage)"
        - name: DOCKERFILE
          value: "$(tasks.generate-docker-files.results.appDockerfile)"
        - name: CONTEXT
          value: "$(tasks.setup.results.contextDir)/$(tasks.wildfly-glow-generate-provision.results.provisioning)"
        - name: TLSVERIFY
          value: "false"
      runAfter: 
        - build-server-image
      workspaces:
        - name: source
          workspace: shared-data
        - name: dockerconfig
          workspace: dockerconfig
    - name: git-create-branch-and-push
      taskRef:
        name: git-cli
        kind: ClusterTask
      params:
        - name: GIT_USER_NAME
          value: jfdenise
        - name: GIT_USER_EMAIL
          value: jfdenise@gmail.com
        - name: GIT_SCRIPT
          value: |
           cd $(tasks.setup.results.contextDir) 
           git config --global --add safe.directory /workspace/source/$(tasks.setup.results.contextDir)
           rev=$(tasks.wildfly-glow-generate-provision.results.gitRevision)
           exists=`git ls-remote --heads git@github.com:jfdenise/go-to-openshift "refs/heads/${rev}" | wc -l`
           if [ "${exists}" = "1" ]; then
             echo "A branch already exists"
             git fetch origin "$(tasks.wildfly-glow-generate-provision.results.gitRevision)"
             git checkout "$(tasks.wildfly-glow-generate-provision.results.gitRevision)"
           else
             git checkout -b "$(tasks.wildfly-glow-generate-provision.results.gitRevision)"
           fi
           # Remove all
           rm -rf ./*
           if [ -d  ".s2i" ]; then
             rm -rf .s2i
           fi
           ls -al $(workspaces.input.path)/$(tasks.setup.results.contextDir)/$(tasks.wildfly-glow-generate-provision.results.contentLocation)/
           cp -r $(workspaces.input.path)/$(tasks.setup.results.contextDir)/$(tasks.wildfly-glow-generate-provision.results.contentLocation)/* .
           if [ -d  "$(workspaces.input.path)/$(tasks.setup.results.contextDir)/$(tasks.wildfly-glow-generate-provision.results.contentLocation)/.s2i" ]; then
             cp -rf $(workspaces.input.path)/$(tasks.setup.results.contextDir)/$(tasks.wildfly-glow-generate-provision.results.contentLocation)/.s2i .
           fi
           ls -al .
           git status
           if [ -n "$(git status --porcelain)" ]; then
             git add *
             git add */.*
             git commit -m "Commit from WildFly Glow pipeline"
             git push origin "$(tasks.wildfly-glow-generate-provision.results.gitRevision)"
           else
             echo "No changes to commit";
           fi
      workspaces:
        - name: source
          workspace: internal-repo
        - name: input
          workspace: shared-data
        - name: ssh-directory
          workspace: ssh-creds
      runAfter: 
        - build-app-image
        - git-clone-internal-repo
  finally:
    - name: cleanup
      taskRef:
        name: wildfly-cleanup-task
      params:
        - name: contextDir
          value: "$(tasks.setup.results.contextDir)"
      workspaces:
        - name: sources
          workspace: shared-data
        - name: internal-repo
          workspace: internal-repo

