apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: wildfly-build-image-task
spec:
  params:
   - name: runtimeImageBuildFile
     type: string
   - name: builderImageBuildFile
     type: string
   - name: runtimeImageStreamFile
     type: string
   - name: builderImageStreamFile
     type: string
   - name: builderName
     type: string
   - name: runtimeName
     type: string
  workspaces:
    - name: sources
      description: The src dir
  steps:
    - name: build-image
      securityContext:
        runAsUser: 0
      image: "image-registry.openshift-image-registry.svc:5000/openshift/cli:latest"
      env:
        - name: WORKSPACE_SRC_PATH
          value: $(workspaces.sources.path)
      script: |
        oc apply -f "$WORKSPACE_SRC_PATH/wildfly-glow/resources/$(params.builderImageStreamFile)"
        oc apply -f "$WORKSPACE_SRC_PATH/wildfly-glow/resources/$(params.runtimeImageStreamFile)"
        oc apply -f "$WORKSPACE_SRC_PATH/wildfly-glow/resources/$(params.runtimeImageBuildFile)"
        oc apply -f "$WORKSPACE_SRC_PATH/wildfly-glow/resources/$(params.builderImageBuildFile)"
        oc start-build --wait $(params.builderName)
        oc start-build --wait $(params.runtimeName)
        echo "Image has been built"