apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: wildfly-identify-branch-task
spec:
  params:
    - name: gitRepo
      type: string
    - name: gitRepoOwner
      type: string
    - name: gitRepoProject
      type: string
    - name: gitRevision
      type: string
  results:
    - name: newBranch
      type: string
    - name: branchToPull
      type: string
  steps:
    - name: identify
      securityContext:
        runAsUser: 0
      image: "redhat/ubi8"
      script: |
        gitURI=$(params.gitRepo)/$(params.gitRepoOwner)/$(params.gitRepoProject)
        gitId=$gitURI/revision/$(params.gitRevision)
        newBranch=`tr -s .:@#/ _ <<< "$gitId"`
        code=`curl -s -o /dev/null -w "%{http_code}" https://api.github.com/repos/jfdenise/go-to-openshift/branches/$newBranch`
        branchToPull="main"
        echo "curl return code $code"
        if [ "$code" = "200" ]; then
          branchToPull=$newBranch
        fi
        echo "New branch $newBranch"
        echo "Branch to pull $branchToPull"
        echo -n "$newBranch" > $(results.newBranch.path)
        echo -n "$branchToPull" > $(results.branchToPull.path)
